GET http://host:port/task

###

POST http://host:port/task HTTP/1.1
Content-Type: application/json

{
    "name": "teste"
}

###

PUT http://host:port/task/2 HTTP/1.1
Content-Type: application/json

{
    "completed": true
}

###

DELETE http://host:port/task/1 HTTP/1.1

###
